version: '3.8'

services:
  vue:
    build: ./Services/Frontend
    image: transcendence_frontend_login
    ports:
      - "8080:8080"
    volumes:
      - ./Volumes/Frontend/Vue/Trascendence:/Trascendence
      - ./Volumes/Frontend/Logs/:/Logs
  login:

    build: 
      context: Services/Backend/login
      dockerfile: Dockerfile

    depends_on:
      - postgres
    image: transcendence_backend_login
    environment:
      - ADMIN
      - LOGIN_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - SECRET_KEY
      - ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES

    ports:
      - 25671:25671

    volumes:
      - v_login:/app
      - v_login_log:/log

    entrypoint: ./docker-entrypoint.sh
  
  postgres:  
    container_name: transcendence_bbdd_login 
    image: transcendence_database_login
    build:
      context: ./Services/Database/login/
    restart: always  
    environment:  
      - POSTGRES_USER
      - POSTGRES_PASSWORD 
      - POSTGRES_DB 
      #POSTGRES_INITDB_WALDIR: ./Volumes/Database/login/login_logs
    volumes:
      - v_postgres_data:/var/lib/postgresql/data
    #ports:  
    # - "5432:5432"
   
  grafana:
    image: grafana/grafana:10.3.1-ubuntu
    container_name: grafana
    restart: unless-stopped
    volumes:
    - ./Volumes/Devops/Grafana/Grafana-data:/var/lib/grafana
    ports:
    - 3000:3000

  prometheus:
    image: bitnami/prometheus:2.49.1-debian-11-r6
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ./Volumes/Devops/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./Volumes/Devops/Prometheus/Prometheus-data:/prometheus
    ports:
    - 9090:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=1y'
    - '--web.enable-lifecycle'

  node_exporter:
    image: quboleinc/node_exporter:release-branch-60.0
    container_name: node_exporter
    restart: unless-stopped
    ports:
    - 9100:9100
    command:
     - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
  
        
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    restart: unless-stopped
    expose:
    - 7070
    platform: linux/amd64
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro


  mail:  
    container_name: transcendence_mail 
    image: transcendence_mail
    build:
      context: ./Services/Mail/
    restart: always
    environment:
      - SMTP_USER
      - SMTP_PASS
    ports:
      - 25:25 

volumes:
        v_login:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ./Volumes/Backend/login/data

        v_login_log:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ./Volumes/Backend/login/log
        v_postgres_data:

        grafana-data:
        prometheus-data:
        

