version: '3.8'

services:

  vue:
    build: ./Services/Frontend
    image: transcendence_frontend_login
    ports:
      - "8080:8080"
    volumes:
      - ./Volumes/Frontend/Vue/Trascendence:/Trascendence
      - ./Volumes/Frontend/Logs/:/Logs

  login:
    build: 
      context: Services/Backend/login
      dockerfile: Dockerfile

    depends_on:
      - postgres
    image: transcendence_backend_login
    environment:
      - LOGGER_PARAMS
      - PARAMS
      - LOGIN_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST

    ports:
      - 25671:25671

    volumes:
      - v_login:/app
      - v_login_log:/log
      - v_login_tools:/app/tools

    entrypoint: ./docker-entrypoint.sh
  
  postgres:  
    container_name: transcendence_bbdd_login 
    image: transcendence_database_login
    build:
      context: ./Services/Database/login/
    restart: always  
    environment:  
      - POSTGRES_USER
      - POSTGRES_PASSWORD 
      - POSTGRES_DB 

    volumes:
      - v_postgres_data:/var/lib/postgresql/data

  mail:  
    container_name: transcendence_mail 
    image: transcendence_mail
    build:
      context: ./Services/Mail/
    restart: always
    environment:
      - SMTP_USER
      - SMTP_PASS
    ports:
      - 25:25 
    #ports:  
    # - "5432:5432"
   
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    restart: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - 3000:3000

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ./Services/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    ports:
    - 9090:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=1y'
    - '--web.enable-lifecycle'

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
    - 9100:9100
    command:
     - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
  
        
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    expose:
    - 8080
    platform: linux/amd64
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro


volumes:
        v_login:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ./Volumes/Backend/login/data

        v_login_log:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ./Volumes/Backend/login/log

        v_login_tools:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ./Services/Backend/login/tools

        v_postgres_data:

        grafana-data:
        prometheus-data:
        

