version: '3.8'
services:
  vue:
    build: ./Services/frontend
    ports:
      - "8080:8080"
    volumes:
      - ./Volumes/Frontend/Vue/Trascendence:/Trascendence
      - ./Volumes/Frontend/Logs/:/Logs

