version: '3.8'

services:

  vue:
    build: ./Services/Frontend
    image: transcendence_frontend_login
    ports:
      - "8080:8080"
    volumes:
      - ./Volumes/Frontend/Vue/Trascendence:/Trascendence
      - ./Volumes/Frontend/Logs/:/Logs

  login:
    build: 
      context: Services/Backend/login
      dockerfile: Dockerfile

    depends_on:
      - postgres
    image: transcendence_backend_login
    environment:
      - LOGGER_PARAMS
      - PARAMS
      - LOGIN_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST

    ports:
      - 25671:25671

    volumes:
      - v_login:/app
      - v_login_log:/log
      - v_login_tools:/app/tools

    entrypoint: ./docker-entrypoint.sh
  
  postgres:  
    container_name: transcendence_bbdd_login 
    image: transcendence_database_login
    build:
      context: ./Services/Database/login/
    restart: always  
    environment:  
      - POSTGRES_USER
      - POSTGRES_PASSWORD 
      - POSTGRES_DB 

    volumes:
      - v_postgres_data:/var/lib/postgresql/data

  mail:  
    container_name: transcendence_mail 
    image: transcendence_mail
    build:
      context: ./Services/Mail/
    restart: always
    environment:
      - SMTP_USER
      - SMTP_PASS
    ports:
      - 25:25 

volumes:
        v_login:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ./Volumes/Backend/login/data

        v_login_log:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ./Volumes/Backend/login/log

        v_login_tools:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: ./Services/Backend/login/tools

        v_postgres_data:
        

