name: Vault Pipeline

on:
  workflow_dispatch:
    inputs:
      main_option:
        description: 'Choose the main command category'
        required: true
        type: choice
        options:
          - Get Unseal Keys
          - Restart Vault (Existing secrets K.O)
          - Introduce new secret
          - Get Secrets