version: '3.8'  
services:  
  postgres_db:  
    container_name: bbdd_login 
    image: postgres_login
    build:
      context: /Users/edurne/Desktop/trans/Services/BBDD/login/
    restart: always  
    environment:  
      POSTGRES_USER: trans  
      POSTGRES_PASSWORD: trans 
      POSTGRES_DB: login_db 
      POSTGRES_INITDB_WALDIR: /Users/edurne/Desktop/trans/Volumes/BBDD/login/login_logs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #ports:  
    # - "5432:5432"
volumes:
  postgres_data:
