services:

  vue:
    build: vue/build/main
    image: transcendence_vue_login
    ports:
      - "8080:8080"
    networks:
      - transcendence
    volumes:
      - vue_data:/Trascendence
      - vue_log:/Logs

  login:
    build: django/build/login
    depends_on:
      - pg-login
    image: transcendence_dj_login
    expose:
        - 25671
    networks:
      - transcendence
    volumes:
      - login_data:/app
      - django_log:/log

  gateway:
    build: django/build/gateway

    depends_on:
      - pg-login
      - login
    image: transcendence_dj_gateway


    ports:
      - 4242:4242

    networks:
      - transcendence
    volumes:
      - gateway_data:/app
      - django_log:/log

  pg-login:
    container_name: transcendence_pg_login
    image: transcendence_pgbase_login
    build: django/build/pg-login
    restart: always
    volumes:
      - pg-login_data:/var/lib/postgresql/data

volumes:

  gateway_data:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: django/volume/gateway

  login_data:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: django/volume/login

  django_log:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: django/log

  vue_log:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: vue/log

  vue_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: vue/volume/main

  pg-login_data:

networks:
  transcendence: 
