services:

  vue:
    build: vue/build/main
    image: transcendence_vue_login
    expose:
      - 8080
    networks:
       - transcendence
    volumes:
      - vue_data:/Trascendence
      - vue_log:/Logs

  user:
    build:
      context: django/build/user
      args:
        - VAULT_TOKEN=$VAULT_TOKEN
        - ADMIN=$ADMIN

    container_name: transcendence_dj_user
    depends_on:
      - pg-login

    image: transcendence_dj_user
    expose:
        - 22748
    networks:
      - transcendence
    volumes:
      - user_data:/app
      - django_log:/log

  login:
    build:
      context: django/build/login
      args:
        - VAULT_TOKEN=$VAULT_TOKEN

    container_name: transcendence_dj_login
    depends_on:
      - pg-login
    image: transcendence_dj_login
    expose:
        - 25671
    networks:
      - transcendence
    volumes:
      - login_data:/app
      - django_log:/log

  gateway:
  
    build:
      context: django/build/gateway
      args:
        - VAULT_TOKEN=$VAULT_TOKEN
    container_name: transcendence_dj_gateway

    depends_on:
      - pg-login
      - login
    image: transcendence_dj_gateway

    expose:
      - 4242

    networks:
      - transcendence
    volumes:
      - gateway_data:/app
      - django_log:/log

  pg-login:
    build: django/build/pg-login
    container_name: transcendence_pg_login
    image: transcendence_pgbase_login
    networks:
      - transcendence
    restart: always
    volumes:
      - pg-login_data:/var/lib/postgresql/data

volumes:

  user_data:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: django/volume/user

  gateway_data:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: django/volume/gateway

  login_data:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: django/volume/login

  django_log:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: django/log

  vue_log:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: vue/log

  vue_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: vue/volume/main

  pg-login_data:

networks:
  transcendence: 
