name: Dependencies Pipeline

on:
  workflow_dispatch:
    inputs:
      main_option:
        description: 'Choose the main command category'
        required: true
        default: 'Vault'
        type: choice
        options:
          - Vault
          - Nginx
          - Haproxy
          - Email
      vault_sub_option:
        description: 'Choose the specific Vault command'
        required: false
        type: choice
        options:
          - Get Unseal Keys
          - Restart Vault (Existing secrets K.O)
          - Introduce new secret
          - Get Secrets
      email_sub_option:
        description: 'Choose the specific Email command'
        required: false
        type: choice
        options:
          - Send Email
          - Check Email Status

jobs:
  handle-vault:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.main_option == 'Vault' }}
    steps:
      - name: Vault command selected
        run: | echo "Vault command: ${{ github.event.inputs.vault_sub_option }}"

  handle-email:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.main_option == 'Email' }}
    steps:
      - name: Email command selected
        run: |
        echo "Email command: ${{ github.event.inputs.email_sub_option }}"