name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Ajusta esto a tu rama de producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to Hostinger
      run: |
        sshpass -p ${{ secrets.HOSTINGER_PASSWORD }} ssh root@195.35.48.173 "comandos para desplegar tu aplicación"
      shell: bash