name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH and Deploy
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        ssh-keyscan -H 195.35.48.173 >> ~/.ssh/known_hosts
        sshpass -p ${{ secrets.HOSTINGER_PASSWORD }} ssh -o StrictHostKeyChecking=no root@195.35.48.173 "comandos para desplegar tu aplicación"
      shell: bash
