name: Email Pipeline

on:
  workflow_dispatch:
    inputs:
      email_command:
        description: 'Choose the specific Email command'
        required: true
        type: choice
        options:
          - Test email
          - Change config (DKIM, SPF, DMARC, MX)
      recipient_email:
        description: 'Recipient Email'
        required: false
        type: string
      email_subject:
        description: 'Email Subject'
        required: false
        type: string
      email_body:
        description: 'Email Body'
        required: false
        type: string
      dkim_config:
        description: 'DKIM Configuration'
        required: false
        type: string
      spf_config:
        description: 'SPF Configuration'
        required: false
        type: string
      dmarc_config:
        description: 'DMARC Configuration'
        required: false
        type: string
      mx_config:
        description: 'MX Configuration'
        required: false
        type: string

jobs:
  handle-email:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Check selected command
        id: check_command
        run: |
          echo "Selected command: ${{ github.event.inputs.email_command }}"
          
          if [[ "${{ github.event.inputs.email_command }}" == "Test email" ]]; then
            echo "Testing email with: ${{ github.event.inputs.test_email }}"
            echo "curl -X POST http://localhost:5000/send-email -H \"recipient: ${{ github.event.inputs.test_email }}\" -H \"subject: Test Email\" -F \"body=This is a test email.\""
            echo "::set-output name=command::Test email"
          elif [[ "${{ github.event.inputs.email_command }}" == "Change config (DKIM, SPF, DMARC, MX)" ]]; then
            echo "Changing configurations"
            echo "DKIM: ${{ github.event.inputs.dkim_config }}"
            echo "SPF: ${{ github.event.inputs.spf_config }}"
            echo "DMARC: ${{ github.event.inputs.dmarc_config }}"
            echo "MX: ${{ github.event.inputs.mx_config }}"
            echo "::set-output name=command::Change config"
          
      - name: Execute Test Email Command
        if: steps.check_command.outputs.command == 'Test email'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            curl -X POST http://localhost:5000/send-email \
              -H "recipient: ${{ github.event.inputs.test_email }}" \
              -H "subject: Test Email" \
              -F "body=This is a test email."
          EOF

      - name: Execute Change Config Command
        if: steps.check_command.outputs.command == 'Change config'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Here you can add commands to update the DKIM, SPF, DMARC, and MX settings
            echo "Updating DKIM: ${{ github.event.inputs.dkim_config }}"
            echo "Updating SPF: ${{ github.event.inputs.spf_config }}"
            echo "Updating DMARC: ${{ github.event.inputs.dmarc_config }}"
            echo "Updating MX: ${{ github.event.inputs.mx_config }}"
            # Example of updating configurations
            # curl -X POST http://localhost:5000/update-config -F "dkim=${{ github.event.inputs.dkim_config }}" -F "spf=${{ github.event.inputs.spf_config }}" -F "dmarc=${{ github.event.inputs.dmarc_config }}" -F "mx=${{ github.event.inputs.mx_config }}"
          EOF
