name: Deploy to Hostinger

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH and Deploy
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        mkdir -p ~/.ssh
        ssh-keyscan -H 195.35.48.173 >> ~/.ssh/known_hosts
        - name: Deploy to Hostinger
        sshpass -p ${{ secrets.HOSTINGER_PASSWORD }} rsync -av --delete --exclude='.git*' ./ root@195.35.48.173:/var/www/trascendence.tech/
      shell: bash
