name: Scheduled Reload

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta a las 12 de la noche UTC
  workflow_dispatch:

jobs:
  reload:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo .env
        run: |
          touch .env
          echo "${{ secrets.ENVIRON }}" > .env
      - name: Conectar al servidor y ejecutar script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf var/www/trascendence.tech
            git clone https://github.com/Julen-Smith/Transcendence.git var/www/trascendence.tech
            cd var/www/trascendence.tech
            mkdir /var/www/trascendence.tech/Volumes/Backend/login/data
            mkdir /var/www/trascendence.tech/Volumes/Backend/login/log
            docker compose down
            docker compose up -d