name: Specific service deploy.

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: "Servicio a desplegar"
        options:
          - transcendence_frontend
          - transcendence_mail
          - transcendence_backend_login
          - transcendence_bbdd_login
        required: true
      branch:
        type: string
        description: "Nombre de la rama o hash del commit para desplegar"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      transcendence_frontend_service: 'Services/Frontend/'
      transcendence_frontend_volume: 'Volumes/Frontend/'
      transcendence_mail_service: 'Services/Mail/'
      transcendence_mail_volume: 'Volumes/Mail/'
      transcendence_backend_login_service: 'Services/Backend/login'
      transcendence_backend_login_volume: 'Volumes/Backend/login'
      transcendence_bbdd_login_service: 'Services/Database/Login'
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Listar Contenido Clonado
        run: ls -la