name: Specific service deploy.

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: "Servicio a desplegar"
        options:
          - transcendence_frontend
          - transcendence_mail
          - transcendence_backend_login
          - transcendence_bbdd_login
        required: true
      branch:
        type: string
        description: "Nombre de la rama o hash del commit para desplegar"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      transcendence_frontend_service: 'Services/Frontend/'
      transcendence_frontend_volume: 'Volumes/Frontend/'
      transcendence_mail_service: 'Services/Mail/'
      transcendence_mail_volume: 'Volumes/Mail/'
      transcendence_backend_login_service: 'Services/Backend/login'
      transcendence_backend_login_volume: 'Volumes/Backend/login'
      transcendence_bbdd_login_service: 'Services/Database/Login'
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Listar Contenido Clonado
        run: ls -la
      
      - name: Establecer Variables de Entorno Específicas del Servicio
        run: |
          if [ "${{ github.event.inputs.service }}" == "transcendence_frontend" ]; then
            echo "SERVICE_PATH=${{ env.transcendence_frontend_service }}" >> $GITHUB_ENV
            echo "SERVICE_VOLUME=${{ env.transcendence_frontend_volume }}" >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV


      - name: Subir Archivos al Servidor
        run : |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}"  > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          pwd
          rsync -avz ${{ github.workspace }}/${SERVICE_PATH}}/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/trascendence.tech/${{ SERVICE_PATH }}/

      - name: Despliegue en VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/trascendence.tech/${{ github.event.inputs.service }}
            docker-compose down ${{ github.event.inputs.service }}
            docker-compose up -d ${{ github.event.inputs.service }}