name: Vault Pipeline

on:
  workflow_dispatch:
    inputs:
      vault_options:
        description: 'Choose the specific Vault command'
        required: true
        type: choice
        options:
          - Get Unseal Keys [MAIL]
          - Get Secret Backup [MAIL]
          - Restart Vault (Actual K.O)

jobs:
  handle-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check selected command
        id: check_command
        run: |
          echo "Selected command: ${{ github.event.inputs.vault_option }}"
          
          if [[ "${{ github.event.inputs.vault_option }}" == "Restart Vault (Actual K.O)" ]]; then
            echo "Vamo"
          elif [[ "${{ github.event.inputs.vault_option }}" == "Get Secret Backup [MAIL]" ]]; then
            echo "Vamo2"
          fi 