name: Vault Pipeline

on:
  workflow_dispatch:
    inputs:
      vault_options:
        description: 'Choose the specific Vault command'
        required: true
        type: choice
        options:
          - Get Unseal Keys [MAIL]
          - Get Secrets Backup [MAIL]
      recipient_email:
        description: 'Recipient Email'
        required: true
        type: string

jobs:
  handle-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check selected command
        id: check_command
        run: |
          echo "Selected command: ${{ github.event.inputs.vault_options }}"
          if [[ "${{ github.event.inputs.vault_options }}" == "Get Unseal Keys [MAIL]" ]]; then
            echo "::set-output name=command::Get Unseal Keys [MAIL]"
          elif [[ "${{ github.event.inputs.vault_options }}" == "Get Secrets Backup [MAIL]" ]]; then
            echo "::set-output name=command::Get Secrets Backup [MAIL]"
          fi

      - name: Send unseal keys
        if: steps.check_command.outputs.command == 'Get Unseal Keys [MAIL]'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            curl -X POST http://localhost:5000/send-email \
              -H "recipient: ${{ github.event.inputs.recipient_email }}" \
              -H "subject: The Seal of the Seal of the Vault has been unsealed." \
              -F "body= <p>Here are the unseal keys:</p><img src='https://th-thumbnailer.cdn-si-edu.com/-gQ0Mexh5E5Vd64bn2hy61B3Pog=/1000x750/filters:no_upscale():focal(800x602:801x603)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer_public/3a/fb/3afb3353-3a1b-4314-a0ee-93d37a1d9b66/gettyimages-1246951746_web.jpg' />" \
              -F "seal_tokens.txt=@/Transcendence/Dependencies/dependencies/dev_secrets.txt"
          EOF