name: Vault Pipeline

on:
  workflow_dispatch:
    inputs:
      vault_options:
        description: 'Choose the specific Vault command'
        required: true
        type: choice
        options:
          - Get Unseal Keys [MAIL]
          - Get Secrets Backup [MAIL]
      recipient_email:
        description: 'Recipient Email'
        required: true
        type: string

jobs:
  handle-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check selected command
        id: check_command
        run: |
          echo "Selected command: ${{ github.event.inputs.vault_options }}"
          if [[ "${{ github.event.inputs.vault_options }}" == "Get Unseal Keys [MAIL]" ]]; then
            echo "::set-output name=command::Get Unseal Keys [MAIL]"
          elif [[ "${{ github.event.inputs.vault_options }}" == "Get Secrets Backup [MAIL]" ]]; then
            echo "::set-output name=command::Get Secrets Backup [MAIL]"
          fi

      - name: Send unseal keys
        if: steps.check_command.outputs.command == 'Get Unseal Keys [MAIL]'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            curl -X POST http://localhost:5000/send-email \
              -H "recipient: ${{ github.event.inputs.recipient_email }}" \
              -H "subject: The Seal of the Seal of the Vault has been unsealed." \
              -F "body= https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.smithsonianmag.com%2Fscience-nature%2Fwhy-did-seals-and-sea-lions-never-commit-to-a-life-fully-at-sea-180983926%2F&psig=AOvVaw1Hf0B12Vk5QvMD4z-aeEO9&ust=1716576636531000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCNiklri4pIYDFQAAAAAdAAAAABAE" \
              -F "seal_tokens.txt=@/Transcendence/Dependencies/dependencies/dev_secrets.txt"
          EOF